#! /bin/sh
# postrm script for dns-cache-monitor
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


. /usr/share/debconf/confmodule
case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        if [ "$1" = purge ]; then
	    update-rc.d dns-cache-monitor remove >/dev/null || exit
	    rm -f /etc/default/dns-cache-monitor
	    rm -f /var/run/dns-cache-monitor*
	fi
	db_purge || true
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac
exit 0
